# The URL the site will be built for
base_url = "https://example.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "hook"
title = "Jiayi Zhou"
description = "This is my personal website."

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
links = [
    { title = "Mail", href = "mailto:nancyzhou36@gmail.com" },
    { title = "GitHub", href = "https://github.com/JiayiZhou36" },
    { title = "LinkedIn", href = "https://www.linkedin.com/in/jiayi-zhou-0b6805197/" }
]